---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.11.2021 20:20
---
--[[
Концентрируется внутри себя, ожидая 3 секунды. Затем быстро выстреливает 6 ударами, каждый удар при попадании по противнику взрывается в области 150.
Можно прервать заряд (копит 1 удар каждые 0.5 сек)
]]
function ChargeShoot(unit)
    local data = GetUnitData(unit)
    data.QPowerShotBreak = false
    local chargeMaxTime = 3
    local chargePeriod = 0.5
    TimerStart(CreateTimer(), 0, false, function()
        StunUnit(unit, chargeMaxTime)
        SetUnitTimeScale(unit, 0.1)
        SetUnitAnimationByIndex(unit, 5)
    end)
    local charge = 0
    local chargeCount = 0
    local chargeTimer = CreateTimer()
    local chargeTimerChecker=CreateTimer()
    TimerStart(chargeTimer, chargePeriod, true, function()
        chargeCount = chargeCount + 1
        charge = charge + chargePeriod
        if not data.QPowerShotBreak then
            if charge >= chargeMaxTime then
                --print("полный каст способности")
                CreateSpeedAttack(unit, chargeCount)
                DestroyTimer(GetExpiredTimer())
                DestroyTimer(chargeTimerChecker)
            end
        end
    end)
    --таймер отлова события отмены анимы
    TimerStart(chargeTimerChecker, TIMER_PERIOD64, true, function()
        if data.QPowerShotBreak then
            DestroyTimer(GetExpiredTimer())
            DestroyTimer(chargeTimer)
            --print("способность прервана дострочно, накоплено выстрелов", chargeCount)
            CreateSpeedAttack(unit, chargeCount)
        end
    end)
end

function CreateSpeedAttack(unit, attackCount)
    StunUnit(unit, 10) -- 10 значение от балды, ну типа не важно на сколько станим, ведь стан управление будет вернуто досрочно
    print("делаем ", attackCount, "быстрых аттак")
    local speedAttackPeriod = 0.2
    SetUnitTimeScale(unit, 3)
    SpeedAttackSingle(unit)
    TimerStart(CreateTimer(), speedAttackPeriod, true, function()
        attackCount = attackCount - 1
        if attackCount <= 0 then
            DestroyTimer(GetExpiredTimer())
            SetUnitTimeScale(unit, 1)
            ResetUnitAnimation(unit)
            UnitClearStun(unit)
        else
            SpeedAttackSingle(unit)
        end

    end)
end

function SpeedAttackSingle(unit)
    SetUnitAnimationByIndex(unit, 0)
    CreateAndForceBullet(unit, GetUnitFacing(unit), 40, "Abilities\\Weapons\\Mortar\\MortarMissile.mdl",nil,nil,150)
end