---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.10.2021 18:44
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), .5, false, function()
            DestroyTimer(GetExpiredTimer())
            --HideEverything()
            --ReturnFPS()
            --MenuFrame()
            --CreateAndStartClock()
        end)

    end
end

TIMER_PERIOD = 1 / 32
TIMER_PERIOD64 = 1 / 64
