---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.08.2021 19:03
---
function normal_sound (s, x, y, volume)
    local snd = CreateSound(s, false, false, false, 10, 10, "")
    if not volume then
        volume = 127
    end
    if not x then
        x = 0
    end
      if not y then
        y = 0
    end
    SetSoundChannel(snd, 1)
    SetSoundVolume(snd, volume)
    StartSound(snd)
    --KillSoundWhenDone(snd)
    return snd
end